# Copyright (c) 2026 The neuraLQX Authors - All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from __future__ import annotations

import math

from collections.abc import Iterable

from neuralqx.utils.typing import CoordinateVertex
from neuralqx.utils.typing import Edge
from neuralqx.utils.typing import EdgeLike
from neuralqx.utils.typing import FamilyEdge
from neuralqx.utils.typing import Vertex


def require_int(name: str, value: int, *, minimum: int) -> None:
    """Validates an integer-valued graph-family parameter.

    Args:
        name: Parameter name used in exception messages.
        value: Candidate value supplied by the caller.
        minimum: Smallest accepted integer value.

    Raises:
        TypeError: If ``value`` is a boolean or non-integer object.
        ValueError: If ``value`` is smaller than ``minimum``.
    """
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer; got {value!r}.")
    if value < minimum:
        raise ValueError(f"{name} must be at least {minimum}; got {value}.")


def vertex(x: float, y: float, z: float = 0.0) -> CoordinateVertex:
    """Returns a normalized coordinate vertex triple.

    Args:
        x: X coordinate.
        y: Y coordinate.
        z: Z coordinate. Defaults to the planar value ``0.0``.

    Returns:
        A three-item coordinate tuple with all entries converted to ``float``.
    """
    return (float(x), float(y), float(z))


def index_to_label(index: int) -> CoordinateVertex:
    """Maps a dense integer label to a deterministic 3D coordinate.

    Args:
        index: Non-negative dense vertex index.

    Returns:
        Coordinate triple used when a graph family is relabelled for
        non-planar conventions.
    """
    group = index // 4
    remainder = index % 4
    return (float(group), float((remainder >> 1) & 1), float(remainder & 1))


def relabel_edges_to_nonplanar(
    edges: Iterable[EdgeLike],
) -> tuple[
    list[tuple[CoordinateVertex, CoordinateVertex, int]], dict[Vertex, CoordinateVertex]
]:
    """Relabels edge endpoints to deterministic 3D coordinate labels.

    Args:
        edges: Edge-like objects whose vertices should receive compact
            non-planar labels.

    Returns:
        A pair containing the relabelled keyed edges and the vertex mapping
        used to produce them. Edge orientation and parallel-edge keys are
        preserved.
    """
    canonical_edges = [Edge.from_like(edge) for edge in edges]
    vertices: list[Vertex] = []
    seen: set[Vertex] = set()
    for edge in canonical_edges:
        for item in edge.vertices:
            if item in seen:
                continue
            vertices.append(item)
            seen.add(item)

    mapping = {item: index_to_label(index) for index, item in enumerate(vertices)}
    relabelled = [
        (mapping[edge.start], mapping[edge.end], edge.key) for edge in canonical_edges
    ]
    return relabelled, mapping


def maybe_relabel_nonplanar(
    edges: Iterable[EdgeLike],
    *,
    non_planar: bool,
) -> list[EdgeLike]:
    """Applies deterministic non-planar relabelling when requested.

    Args:
        edges: Edge-like objects generated by a graph-family constructor.
        non_planar: Whether to replace the family coordinates with compact
            deterministic 3D labels.

    Returns:
        Relabelled edge objects when ``non_planar`` is ``True``. Otherwise the
        original edge list is returned as a list.
    """
    edge_list = list(edges)
    if not non_planar:
        return edge_list
    relabelled, _ = relabel_edges_to_nonplanar(edge_list)
    return relabelled


def circular_vertices(
    count: int,
    *,
    radius: float = 1.0,
    angle_offset: float = 0.0,
) -> list[CoordinateVertex]:
    """Returns evenly spaced planar vertices on a circle.

    Args:
        count: Number of vertices to generate.
        radius: Circle radius.
        angle_offset: Initial angular offset in radians.

    Returns:
        Coordinate triples with zero z coordinate, ordered counterclockwise by
        increasing vertex index.
    """
    return [
        vertex(
            radius * math.cos(angle_offset + 2.0 * math.pi * index / count),
            radius * math.sin(angle_offset + 2.0 * math.pi * index / count),
            0.0,
        )
        for index in range(count)
    ]


def graph_repr(graph: object, **fields: object) -> str:
    """Builds a compact representation for graph-family classes.

    Args:
        graph: Graph-family instance exposing graph count properties.
        **fields: Additional family-specific fields to include.

    Returns:
        A string containing the class name, graph counts, planarity flag, and
        optional family parameters.
    """
    body = [
        f"n_vertices={getattr(graph, 'n_vertices')}",
        f"n_edges={getattr(graph, 'n_edges')}",
    ]
    if hasattr(graph, "n_minimal_loops"):
        body.append(f"n_minimal_loops={getattr(graph, 'n_minimal_loops')}")
    body.append(f"is_planar={getattr(graph, 'is_planar')}")
    body.extend(f"{name}={value!r}" for name, value in fields.items())
    return f"{type(graph).__name__}({', '.join(body)})"


__all__ = [
    "CoordinateVertex",
    "FamilyEdge",
    "circular_vertices",
    "graph_repr",
    "index_to_label",
    "maybe_relabel_nonplanar",
    "relabel_edges_to_nonplanar",
    "require_int",
    "vertex",
]
