# Copyright (c) 2026 The neuraLQX Authors - All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Discrete U(1) gauge constraint.

The constraint checks constructive gauge-fixing relations on flat U(1) state
arrays. Each relation is evaluated independently for every gauge component.
"""

from __future__ import annotations

from typing import Any

import jax
import jax.numpy as jnp

from neuralqx.hilbert.constraint import AbstractDiscreteConstraint
from neuralqx.utils.struct import field

from neuralqx.hilbert.u1.utils.arithmetic import signed_modular_sum

from .relation import GaugeRelation


class U1GaugeConstraint(AbstractDiscreteConstraint):
    """Discrete constraint checking constructive U(1) gauge-fixing relations.

    Args:
        relations: Constructive gauge relations over base graph edges.
        gauge_dimensions: Number of independent U(1) components per edge.
        n_edges: Number of base graph edges.
        q_min: Minimum charge value in the local range.
        step: Charge spacing in the local range.
        local_size: Number of allowed local charge values.
        n_free: Number of independently sampled base edges.

    Attributes:
        relations: Constructive gauge relations over base graph edges.
        gauge_dimensions: Number of independent U(1) components per edge.
        n_edges: Number of base graph edges.
        q_min: Minimum charge value in the local range.
        step: Charge spacing in the local range.
        local_size: Number of allowed local charge values.
        n_free: Number of independently sampled base edges.
    """

    relations: tuple[GaugeRelation, ...] = field(static=True)
    """Constructive gauge relations over base graph edges."""

    gauge_dimensions: int = field(static=True)
    """Number of independent U(1) components per edge."""

    n_edges: int = field(static=True)
    """Number of base graph edges."""

    q_min: int | float = field(static=True)
    """Minimum charge value in the local range."""

    step: int | float = field(static=True)
    """Charge spacing in the local range."""

    local_size: int = field(static=True)
    """Number of allowed local charge values."""

    n_free: int = field(static=True)
    """Number of independently sampled base edges."""

    def __post_init__(self) -> None:
        """Normalizes integer metadata fields."""
        object.__setattr__(self, "relations", tuple(self.relations))
        object.__setattr__(self, "gauge_dimensions", int(self.gauge_dimensions))
        object.__setattr__(self, "n_edges", int(self.n_edges))
        object.__setattr__(self, "local_size", int(self.local_size))
        object.__setattr__(self, "n_free", int(self.n_free))

    def __hash__(self) -> int:
        """Returns a structural hash for the U(1) gauge constraint."""
        return hash(
            (
                type(self),
                self.relations,
                self.gauge_dimensions,
                self.n_edges,
                self.q_min,
                self.step,
                self.local_size,
                self.n_free,
            )
        )

    def validate_hilbert(self, hilbert: Any) -> None:
        """Checks that the target Hilbert space matches this constraint.

        Args:
            hilbert: Candidate U(1) Hilbert space.

        Raises:
            ValueError: If the space's flat state size is inconsistent with
            the stored gauge-component count and base-edge count.
        """
        expected = self.gauge_dimensions * self.n_edges
        if hilbert.size != expected:
            raise ValueError(
                f"U1GaugeConstraint expected Hilbert size {expected}, got {hilbert.size}."
            )

    def dimension(self, hilbert: Any) -> int | None:
        """Returns the exact constructive gauge-fixed dimension.

        Args:
            hilbert: Hilbert space requesting the constrained dimension. The
                argument is accepted for the shared constraint protocol and is
                not needed because all required metadata is stored on the
                constraint.

        Returns:
            Number of valid states generated by assigning every free base edge
            in every gauge component and reconstructing the slave edges.
        """
        return int(self.local_size) ** (int(self.gauge_dimensions) * int(self.n_free))

    def __call__(self, states: Any) -> jax.Array:
        """Evaluates all constructive gauge relations on U(1) states.

        Args:
            states: Flat U(1) state array. The final axis must contain
                ``gauge_dimensions * n_edges`` scalar charges.

        Returns:
            Boolean mask over the leading batch axes. A row is accepted when
            every slave edge equals the signed modular sum prescribed by every
            relation in every gauge component.
        """
        arr = jnp.asarray(states)
        single = arr.ndim == 1
        flat_size = self.gauge_dimensions * self.n_edges
        arr2 = arr[None, :] if single else arr.reshape((-1, flat_size))
        ok = jnp.ones((arr2.shape[0],), dtype=jnp.bool_)
        for relation in self.relations:
            ok = ok & _relation_satisfied(self, arr2, relation)
        return ok[0] if single else ok.reshape(arr.shape[:-1])


def _relation_satisfied(
    constraint: U1GaugeConstraint,
    states: jax.Array,
    relation: GaugeRelation,
) -> jax.Array:
    """Checks one gauge relation across all gauge dimensions."""
    ok = jnp.ones((states.shape[0],), dtype=jnp.bool_)
    for gauge in range(constraint.gauge_dimensions):
        lhs_site = gauge * constraint.n_edges + relation.lhs
        rhs_sites = jnp.asarray(
            [gauge * constraint.n_edges + edge for edge, _ in relation.rhs],
            dtype=jnp.int32,
        )
        signs = jnp.asarray([sign for _, sign in relation.rhs], dtype=states.dtype)
        rhs = signed_modular_sum(
            jnp.take(states, rhs_sites, axis=-1),
            signs,
            q_min=constraint.q_min,
            step=constraint.step,
            local_size=constraint.local_size,
            dtype=states.dtype,
        )
        ok = ok & (states[:, lhs_site] == rhs)
    return ok
