

#
#
#   Configuration file for the Sphinx documentation builder.

import os
import sys
import shutil
import inspect

os.environ["NQX_EXPERIMENTAL"]="1"

import neuralqx as nqx

ROOT = os.path.abspath("..")
sys.path.insert(0, ROOT)

#
#
#   Project information

project = 'neuraLQX'
copyright = '2026, The neuraLQX Authors - All Rights Reserved'
author = 'The neuraLQX Authors'

release = nqx.__version__

#
#
#   General configuration

extensions = [
    "sphinx_design",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx_copybutton",
    "myst_nb",
    "sphinx_autodoc_typehints",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.graphviz",
]

autodoc_docstring_signature = True
autodoc_inherit_docstrings = True
autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
    "imported-members": False,
}
autodoc_member_order = "bysource"
allow_inherited = True
autosummary_generate = True
napoleon_preprocess_types = True
napoleon_attr_annotations = True
toc_object_entries_show_parents = "hide"
add_module_names = False

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', "**.ipynb_checkpoints", "README.md"]
source_suffix = [".rst", ".ipynb", ".md"]

myst_enable_extensions = [
    "dollarmath",
    "amsmath",
    "colon_fence",
    "html_admonition",
    "substitution",
    "deflist",
    "fieldlist",
    "tasklist",
    "deflist",
    "html_image",
]

myst_update_mathjax = False
mathjax_path = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
myst_heading_anchors = 2
autosectionlabel_maxdepth = 1

#
#
#   Options for HTML output

intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "netket": ("https://netket.readthedocs.io/en/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "jax": ("https://jax.readthedocs.io/en/latest/", None),
    "flax": ("https://flax-linen.readthedocs.io/en/latest/", None),
}

html_theme = 'shibuya'
html_static_path = ['_static']
html_title = "neuraLQX: high-performance simulations toolkit for LQG"
html_short_title = "neuraLQX"
html_logo = "_static/logo_banner_tbg.png"
html_css_files = [
    "custom.css",
]
# html_favicon = "_static/favicon.ico"

html_theme_options = {
    "light_logo": "_static/logo_banner_tbg.png",
    "dark_logo": "_static/logo_banner_tbg.png",
    "logo_target": "https://neuralqx.readthedocs.io/en/latest/",
    "github_url": "https://github.com/waleed-sh/neuraLQX.git",
    "accent_color": "teal",
    "color_mode": "light",
    "page_layout": "default",
    "announcement": "This package is still under development. Stay tuned for the release!",
    "globaltoc_expand_depth": 0,
}

nb_execution_mode = "off"
nb_execution_allow_errors = False

nb_render_markdown_format = "myst"
nb_merge_streams = True


#
#
#   Autogenerated public API

HERE = os.path.abspath(os.path.dirname(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))

sys.path.insert(0, ROOT)

def run_apidoc(app):
    try:
        from sphinx.ext.apidoc import main as apidoc_main
    except Exception:
        from sphinx.apidoc import main as apidoc_main

    out_dir = os.path.join(HERE, "documentation", "api", "generated")
    pkg_dir = os.path.join(ROOT, "neuralqx")

    if os.path.isdir(out_dir):
        shutil.rmtree(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    # -f force, -e separate pages, -M module-first
    apidoc_main([
        "-f",
        "-e",
        "-M",
        "-o", out_dir,
        pkg_dir,
        os.path.join(pkg_dir, "tests"),
    ])

def skip_imported(app, what, name, obj, skip, options):
    cur_mod = getattr(app.env, "temp_data", {}).get("autodoc:module")
    if not cur_mod:
        return skip

    mod = sys.modules.get(cur_mod)

    allow = getattr(mod, "__all__", None)
    if allow is not None:
        return False if name in allow else True

    obj_mod = getattr(obj, "__module__", None)
    if obj_mod and obj_mod != cur_mod:
        return True

    if inspect.ismodule(obj):
        return True

    return skip

def setup(app):
    app.connect("builder-inited", run_apidoc)
    app.connect("autodoc-skip-member", skip_imported)


